language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache: false

jobs:
  include:
    # we can only frontend tests from the ether/ organization and not from forks.
    # To request tests to be run ask a maintainer to fork your repo to ether/
    - if: fork = false
    - name: "Test rate limit"
      install:
        - "docker network create --subnet=172.23.42.0/16 ep_net"
        - "docker build -f Dockerfile -t epl-debian-slim ."
        - "docker build -f tests/ratelimit/Dockerfile.nginx -t nginx-latest ."
        - "docker run -p 8081:80 --rm --network ep_net --ip 172.23.42.1 -d nginx-latest"
        - "docker run -p 9000:9001 --rm --network ep_net --ip 172.23.42.2 -d epl-debian-slim"
        - "./bin/installDeps.sh"
      script:
        - "cd tests/ratelimit && bash testlimits.sh"
